#!/usr/bin/env bash
# Shared helpers for OpenSearch semantic search init scripts.
set -euo pipefail

SEMANTIC_TEXT_FIELD="${SEMANTIC_TEXT_FIELD:-atlas_semantic_text}"
SEMANTIC_EMBEDDING_FIELD="${SEMANTIC_EMBEDDING_FIELD:-atlas_semantic_embedding}"
VERTEX_INDEX_NAME="${VERTEX_INDEX_NAME:-janusgraph_vertex_index}"

enable_local_ml_on_data_node() {
  local url="${1:?OpenSearch URL required}"
  echo "==> Allowing ML models on data node (local dev) ..."
  curl -sf -X PUT "${url}/_cluster/settings" \
    -H "Content-Type: application/json" \
    -d '{"persistent":{"plugins.ml_commons.only_run_on_ml_node":false}}' >/dev/null
}

wait_for_opensearch() {
  local url="${1:?OpenSearch URL required}"
  echo "==> Waiting for OpenSearch at ${url} ..."
  for _ in $(seq 1 60); do
    if curl -sf "${url}/_cluster/health" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "OpenSearch is not reachable at ${url}"
  exit 1
}

write_bootstrap_artifact() {
  local artifact_file="${1:?Bootstrap artifact path required}"
  local model_id="${2:?Model id required}"
  local pipeline_name="${3:?Pipeline name required}"
  local dimension="${4:?Embedding dimension required}"

  mkdir -p "$(dirname "${artifact_file}")"
  cat > "${artifact_file}" <<EOF
# Generated by OpenSearch semantic bootstrap. Copy into atlas-application.properties.
MODEL_ID=${model_id}
PIPELINE_NAME=${pipeline_name}
EMBEDDING_DIMENSION=${dimension}
EOF
}

print_atlas_config_guide() {
  local model_id="${1:?Model id required}"
  local pipeline_name="${2:?Pipeline name required}"
  local dimension="${3:?Embedding dimension required}"
  local artifact_file="${4:-}"

  cat <<EOF

==> Set these in atlas-application.properties (must match OpenSearch):

atlas.search.semantic.opensearch.model.id=${model_id}
atlas.search.semantic.opensearch.embedding.dimension=${dimension}

OpenSearch bootstrap applied knn + ingest pipeline (${pipeline_name}) + embedding mapping
on the JanusGraph vertex index (${VERTEX_INDEX_NAME}).
EOF

  if [ -n "${artifact_file}" ]; then
    echo "Reference copy: ${artifact_file}"
  fi
}

wait_for_ml_task() {
  local url="${1:?OpenSearch URL required}"
  local task_id="${2:?Task id required}"
  local result_var="${3:?Result variable name required}"

  echo "==> Waiting for ML task ${task_id} ..."
  local model_id=""
  for _ in $(seq 1 120); do
    local task_response
    task_response=$(curl -sf "${url}/_plugins/_ml/tasks/${task_id}" || true)
    local state
    state=$(echo "${task_response}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('state',''))" 2>/dev/null || echo "")
    if [ "${state}" = "COMPLETED" ]; then
      model_id=$(echo "${task_response}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('model_id',''))")
      break
    fi
    if [ "${state}" = "FAILED" ]; then
      echo "ML task failed: ${task_response}"
      exit 1
    fi
    sleep 3
  done

  if [ -z "${model_id}" ]; then
    echo "Timed out waiting for ML task ${task_id}"
    exit 1
  fi

  printf -v "${result_var}" '%s' "${model_id}"
}

register_remote_model() {
  local url="${1:?OpenSearch URL required}"
  local connector_id="${2:?Connector id required}"
  local model_name="${3:?Remote model name required}"

  echo "==> Registering remote embedding model '${model_name}' ..."
  curl -sf -X POST "${url}/_plugins/_ml/models/_register?deploy=true" \
    -H "Content-Type: application/json" \
    -d "{
      \"name\": \"${model_name}\",
      \"function_name\": \"remote\",
      \"description\": \"Remote embedding model for Atlas semantic search\",
      \"connector_id\": \"${connector_id}\"
    }"
}

get_ml_model_state() {
  local url="${1:?OpenSearch URL required}"
  local model_id="${2:?Model id required}"

  curl -sf "${url}/_plugins/_ml/models/${model_id}" 2>/dev/null | python3 -c "
import sys, json
try:
    doc = json.load(sys.stdin)
except Exception:
    sys.exit(1)
print(doc.get('model_state', ''))
" 2>/dev/null || true
}

find_deployed_local_model_id() {
  local url="${1:?OpenSearch URL required}"
  local model_name="${2:?Model name required}"

  local search_response
  search_response=$(curl -sf -X POST "${url}/_plugins/_ml/models/_search" \
    -H "Content-Type: application/json" \
    -d "{
      \"query\": {
        \"bool\": {
          \"filter\": [
            { \"term\": { \"name.keyword\": \"${model_name}\" } },
            { \"term\": { \"model_state\": \"DEPLOYED\" } }
          ],
          \"must_not\": [
            { \"exists\": { \"field\": \"chunk_number\" } }
          ]
        }
      },
      \"size\": 1,
      \"sort\": [{ \"created_time\": { \"order\": \"desc\" } }]
    }" 2>/dev/null || true)

  if [ -z "${search_response}" ]; then
    return 0
  fi

  local candidate_id
  candidate_id=$(echo "${search_response}" | python3 -c "
import sys, json
try:
    hits = json.load(sys.stdin).get('hits', {}).get('hits', [])
except Exception:
    sys.exit(0)
if not hits:
    sys.exit(0)
source = hits[0].get('_source', {})
print(source.get('model_id') or hits[0].get('_id', ''))
" 2>/dev/null || true)

  if [ -z "${candidate_id}" ]; then
    return 0
  fi

  local state
  state=$(get_ml_model_state "${url}" "${candidate_id}")
  if [ "${state}" = "DEPLOYED" ]; then
    echo "${candidate_id}"
  fi
}

register_local_pretrained_model() {
  local url="${1:?OpenSearch URL required}"
  local model_name="${2:?Model name required}"
  local model_version="${3:?Model version required}"
  local result_var="${4:?Result variable name required}"

  echo "==> Registering and deploying local embedding model (${model_name}) ..."
  local register_response
  register_response=$(curl -sf -X POST "${url}/_plugins/_ml/models/_register?deploy=true" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"${model_name}\",\"version\":\"${model_version}\",\"model_format\":\"TORCH_SCRIPT\"}")

  local task_id
  task_id=$(echo "${register_response}" | python3 -c "import sys,json; print(json.load(sys.stdin).get('task_id',''))")
  if [ -z "${task_id}" ]; then
    echo "Failed to register model: ${register_response}"
    return 1
  fi

  wait_for_ml_task "${url}" "${task_id}" "${result_var}"
}

resolve_local_embedding_model_id() {
  local url="${1:?OpenSearch URL required}"
  local model_name="${2:?Model name required}"
  local model_version="${3:?Model version required}"
  local force_register="${4:-false}"
  local result_var="${5:?Result variable name required}"

  local model_id=""

  if [ "${force_register}" != "true" ]; then
    model_id=$(find_deployed_local_model_id "${url}" "${model_name}")
    if [ -n "${model_id}" ]; then
      echo "==> Reusing deployed ML model ${model_id} (${model_name})"
      printf -v "${result_var}" '%s' "${model_id}"
      return 0
    fi
    echo "==> No DEPLOYED model named '${model_name}' in OpenSearch; registering a new model ..."
  else
    echo "==> --force: registering and deploying a new local embedding model ..."
  fi

  register_local_pretrained_model "${url}" "${model_name}" "${model_version}" model_id
  echo "==> Model deployed: ${model_id}"
  printf -v "${result_var}" '%s' "${model_id}"
}

vertex_index_exists() {
  local url="${1:?OpenSearch URL required}"
  local index_name="${2:?Index name required}"
  curl -sf -o /dev/null -w '%{http_code}' "${url}/${index_name}" | grep -q '^200$'
}

is_vertex_index_knn_enabled() {
  local url="${1:?OpenSearch URL required}"
  local index_name="${2:?Index name required}"
  curl -sf "${url}/${index_name}/_settings/index.knn" | python3 -c "
import sys, json
try:
    root = json.load(sys.stdin)
except Exception:
    sys.exit(1)
for payload in root.values():
    idx = payload.get('settings', {}).get('index', {})
    knn = idx.get('knn', False)
    print(str(knn).lower())
    break
else:
    print('false')
" 2>/dev/null || echo "false"
}

ensure_vertex_index_knn() {
  local url="${1:?OpenSearch URL required}"
  local index_name="${2:?Index name required}"

  if [ "$(is_vertex_index_knn_enabled "${url}" "${index_name}")" = "true" ]; then
    echo "==> knn already enabled on ${index_name}"
    return 0
  fi

  echo "==> Enabling knn on ${index_name} ..."
  curl -sf -X PUT "${url}/${index_name}/_settings" \
    -H 'Content-Type: application/json' \
    -d '{"settings":{"index":{"knn":true}}}'
}

ensure_semantic_ingest_pipeline() {
  local url="${1:?OpenSearch URL required}"
  local model_id="${2:?Model id required}"
  local pipeline_name="${3:?Pipeline name required}"

  echo "==> Ensuring ingest pipeline ${pipeline_name} (model ${model_id}) ..."
  curl -sf -X PUT "${url}/_ingest/pipeline/${pipeline_name}" \
    -H 'Content-Type: application/json' \
    -d "{
      \"description\": \"Atlas semantic search: embed text at ingest on JanusGraph vertex index\",
      \"processors\": [
        {
          \"text_embedding\": {
            \"model_id\": \"${model_id}\",
            \"field_map\": {
              \"${SEMANTIC_TEXT_FIELD}\": \"${SEMANTIC_EMBEDDING_FIELD}\"
            }
          }
        },
        {
          \"remove\": {
            \"field\": \"${SEMANTIC_TEXT_FIELD}\",
            \"ignore_missing\": true
          }
        }
      ]
    }"
}

ensure_semantic_embedding_mapping() {
  local url="${1:?OpenSearch URL required}"
  local index_name="${2:?Index name required}"
  local dimension="${3:?Embedding dimension required}"

  echo "==> Ensuring ${SEMANTIC_EMBEDDING_FIELD} mapping on ${index_name} (dim=${dimension}) ..."
  curl -sf -X PUT "${url}/${index_name}/_mapping" \
    -H 'Content-Type: application/json' \
    -d "{
      \"properties\": {
        \"${SEMANTIC_EMBEDDING_FIELD}\": {
          \"type\": \"knn_vector\",
          \"dimension\": ${dimension},
          \"method\": {
            \"name\": \"hnsw\",
            \"space_type\": \"cosinesimil\",
            \"engine\": \"lucene\"
          }
        }
      }
    }"
}

bootstrap_semantic_vertex_index() {
  local url="${1:?OpenSearch URL required}"
  local model_id="${2:?Model id required}"
  local pipeline_name="${3:?Pipeline name required}"
  local dimension="${4:?Embedding dimension required}"
  local index_name="${5:-${VERTEX_INDEX_NAME}}"

  if ! vertex_index_exists "${url}" "${index_name}"; then
    echo "WARNING: Vertex index '${index_name}' does not exist yet — skipping knn/pipeline/mapping bootstrap."
    echo "         Start Atlas once so JanusGraph creates the index, then re-run this script."
    return 0
  fi

  ensure_vertex_index_knn "${url}" "${index_name}"
  ensure_semantic_ingest_pipeline "${url}" "${model_id}" "${pipeline_name}"
  ensure_semantic_embedding_mapping "${url}" "${index_name}" "${dimension}"
  echo "==> Semantic vertex index bootstrap complete (${index_name})"
}
