#!/usr/bin/env bash
# Shared helpers for OpenSearch semantic search init scripts.
set -euo pipefail

wait_for_opensearch() {
  local url="${1:?OpenSearch URL required}"
  echo "==> Waiting for OpenSearch at ${url} ..."
  for _ in $(seq 1 60); do
    if curl -sf "${url}/_cluster/health" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "OpenSearch is not reachable at ${url}"
  exit 1
}

write_bootstrap_artifact() {
  local artifact_file="${1:?Bootstrap artifact path required}"
  local model_id="${2:?Model id required}"
  local pipeline_name="${3:?Pipeline name required}"
  local dimension="${4:?Embedding dimension required}"

  mkdir -p "$(dirname "${artifact_file}")"
  cat > "${artifact_file}" <<EOF
# Generated by OpenSearch semantic bootstrap. Copy into atlas-application.properties.
MODEL_ID=${model_id}
PIPELINE_NAME=${pipeline_name}
EMBEDDING_DIMENSION=${dimension}
EOF
}

print_atlas_config_guide() {
  local model_id="${1:?Model id required}"
  local pipeline_name="${2:?Pipeline name required}"
  local dimension="${3:?Embedding dimension required}"
  local artifact_file="${4:-}"

  cat <<EOF

==> Set these in atlas-application.properties (must match OpenSearch):

atlas.search.semantic.opensearch.model.id=${model_id}
atlas.search.semantic.opensearch.embedding.dimension=${dimension}

Atlas creates the ingest pipeline (${pipeline_name}) on startup and stores embeddings
on the existing JanusGraph vertex index ({atlas.graph.index.search.index-name}_vertex_index).
EOF

  if [ -n "${artifact_file}" ]; then
    echo "Reference copy: ${artifact_file}"
  fi
}

wait_for_ml_task() {
  local url="${1:?OpenSearch URL required}"
  local task_id="${2:?Task id required}"
  local result_var="${3:?Result variable name required}"

  echo "==> Waiting for ML task ${task_id} ..."
  local model_id=""
  for _ in $(seq 1 120); do
    local task_response
    task_response=$(curl -sf "${url}/_plugins/_ml/tasks/${task_id}" || true)
    local state
    state=$(echo "${task_response}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('state',''))" 2>/dev/null || echo "")
    if [ "${state}" = "COMPLETED" ]; then
      model_id=$(echo "${task_response}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('model_id',''))")
      break
    fi
    if [ "${state}" = "FAILED" ]; then
      echo "ML task failed: ${task_response}"
      exit 1
    fi
    sleep 3
  done

  if [ -z "${model_id}" ]; then
    echo "Timed out waiting for ML task ${task_id}"
    exit 1
  fi

  printf -v "${result_var}" '%s' "${model_id}"
}

register_remote_model() {
  local url="${1:?OpenSearch URL required}"
  local connector_id="${2:?Connector id required}"
  local model_name="${3:?Remote model name required}"

  echo "==> Registering remote embedding model '${model_name}' ..."
  curl -sf -X POST "${url}/_plugins/_ml/models/_register?deploy=true" \
    -H "Content-Type: application/json" \
    -d "{
      \"name\": \"${model_name}\",
      \"function_name\": \"remote\",
      \"description\": \"Remote embedding model for Atlas semantic search\",
      \"connector_id\": \"${connector_id}\"
    }"
}
