# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Slim runtime image: JRE 17 only (not atlas-base with 3 JDKs + Hadoop tooling).
FROM eclipse-temurin:17-jre-jammy

ARG ATLAS_VERSION=3.0.0-SNAPSHOT

ENV ATLAS_SEMANTIC_INDEXER_HOME=/opt/atlas-semantic-indexer
ENV ATLAS_HOME=${ATLAS_SEMANTIC_INDEXER_HOME}
ENV ATLAS_SCRIPTS=/home/atlas/scripts

RUN groupadd -r atlas && useradd -r -g atlas -d /home/atlas -m -s /bin/bash atlas && \
    mkdir -p /home/atlas/dist /home/atlas/scripts /home/atlas/conf/runtime && \
    chown -R atlas:atlas /home/atlas

COPY --chown=atlas:atlas ./dist/apache-atlas-${ATLAS_VERSION}-semantic-indexer.tar.gz /home/atlas/dist/
COPY --chown=atlas:atlas ./scripts/merge-semantic-config.sh ${ATLAS_SCRIPTS}/
COPY --chown=atlas:atlas ./scripts/atlas-semantic-indexer.sh ${ATLAS_SCRIPTS}/

RUN tar xfz /home/atlas/dist/apache-atlas-${ATLAS_VERSION}-semantic-indexer.tar.gz --directory=/opt/ && \
    ln -sf /opt/apache-atlas-${ATLAS_VERSION}-semantic-indexer ${ATLAS_SEMANTIC_INDEXER_HOME} && \
    rm -f /home/atlas/dist/apache-atlas-${ATLAS_VERSION}-semantic-indexer.tar.gz && \
    chown -R atlas:atlas /opt/apache-atlas-${ATLAS_VERSION}-semantic-indexer

USER atlas
WORKDIR ${ATLAS_SEMANTIC_INDEXER_HOME}

ENTRYPOINT ["/home/atlas/scripts/atlas-semantic-indexer.sh"]
